import sys
import os
import logging

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from agents import PsychologicalAgent, IntelAgent, StrategyAgent
from celery import shared_task
import models, database

logger = logging.getLogger(__name__)


@shared_task(
    name="run_agent_analysis",
    autoretry_for=(Exception,),
    retry_backoff=True,
    retry_max_retries=2,
)
def run_agent_analysis(case_id: int):
    db = next(database.get_db())
    case = None
    try:
        case = db.query(models.Case).filter(models.Case.id == case_id).first()
        if not case:
            logger.warning(f"Case {case_id} not found")
            return

        msg = db.query(models.Message).filter(models.Message.id == case.initial_message_id).first()
        if not msg:
            logger.warning(f"Initial message for case {case_id} not found")
            return

        case.status = "analyzing"
        db.commit()

        agent_a = PsychologicalAgent()
        agent_b = IntelAgent()
        agent_c = StrategyAgent()

        res_a = agent_a.analyze(msg.text)
        res_b = agent_b.analyze(msg.text)
        res_c = agent_c.analyze(f"Analysis A: {res_a}\nAnalysis B: {res_b}")

        case.agent_analysis = {
            "agent_a": res_a,
            "agent_b": res_b,
            "agent_c": res_c
        }
        case.status = "analyzed"
        db.commit()

        os.makedirs("data", exist_ok=True)

        from reporting.pdf_generator import generate_pdf_report
        from reporting.email_sender import send_email_with_pdf

        report_path = f"data/case_{case.id}.pdf"
        case_data = {
            "id": case.id,
            "summary": "Case generated by high risk scoring and agent analysis.",
            "risk_score": case.risk_score,
            "status": case.status,
            "user_hash": case.user_hash,
            "agent_analysis": case.agent_analysis
        }
        generate_pdf_report(case_data, report_path)
        send_email_with_pdf(case.id, case.risk_score, report_path)

        logger.info(f"Agent analysis completed for case {case_id}")
    except Exception as e:
        logger.error(f"Error in agent analysis for case {case_id}: {e}")
        if case is not None:
            case.status = "error"
            db.commit()
        raise
